### ISSUE TITLE
I think this is not an issue, but it can work in stm32f103ret6

### ISSUE THREAD

**Issue by yulong88888** [ElectronicCats/mpu6050#26]
Hello !
I am very excited because this library can be used by the stm32f103ret6 platform. The platformio I used was compiled successfully and ran successfully. Thanks for your contributions.

<img width="981" alt="WX20210727-111417@2x" src="https://user-images.githubusercontent.com/22142323/127089640-cd2e5e3a-c9f4-436e-902a-869c84e1d846.png">

My English is not good, this is translated by Google。😀

**Comment by sabas1080** [comment]
Yeih, thanks for notifying us
