### ISSUE TITLE
Accelerometer Word scale factor

### ISSUE THREAD

**Issue by HT-SWRI** [ElectronicCats/mpu6050#36]
Hello,

I don't know if this is a mistake or not, but I thought I should bring it up and ask.

In the datasheet for the MPU6050, it specifies the following:

```
ACCELEROMETER SENSITIVITY
Full-Scale Range
AFS_SEL=0 -> ±2 g
AFS_SEL=1 -> ±4 g
AFS_SEL=2 -> ±8 g
AFS_SEL=3 -> ±16 g

ADC Word Length
AFS_SEL=0 ->16,384 LSB/g
AFS_SEL=1 -> 8,192 LSB/g
AFS_SEL=2 -> 4,096 LSB/g
AFS_SEL=3 -> 2,048 LSB/g
```
However, in the MPU6050.cpp file lines 1817 to 1823 it can be seen that the values for the LSB sensitivity are basically halved and the units are different (LSB/mg):
```
 * <pre>
 * AFS_SEL | Full Scale Range | LSB Sensitivity
 * --------+------------------+----------------
 * 0       | +/- 2g           | 8192 LSB/mg
 * 1       | +/- 4g           | 4096 LSB/mg
 * 2       | +/- 8g           | 2048 LSB/mg
 * 3       | +/- 16g          | 1024 LSB/mg
 * </pre>
```

One final detail, these values were marked as LSB/mg prior to revision 2.2 on the datasheet. This is what leads me to believe this description might be incorrect.

Thanks.

**Comment by Arthulisher** [comment]
Hello HT-SWRI.
ElectronicCats thanks your feedback
 We are open to pull requests in order to allow you to suggest any change in our codes.
Best regards.
