### ISSUE TITLE
esp32 2.0.4 Unlimited waiting for bugs

### ISSUE THREAD

**Issue by bbhxwl** [ElectronicCats/mpu6050#51]
esp32 2.0.4 Unlimited waiting for bugs
```
    mpu.initialize();

```
When the program runs here, it will not run the following code. Arduino for esp32 1.0.6 is normal.

**Comment by Eric286** [comment]
Dear @bbhxwl !
Thank you for contacting us.
To better understand your situation, please, we require the following information:

Could you explain your problem a little more? Since from what I understand the code does not compile you in that line of code.
Can I have the error message?
Have you had this problem before? If so, when?
Has anything changed since this issue started?
Do you experience this issue on another computer\device\network?
What IDE are you using and what version of it?

In the same way, we require you to send us any photograph or video that you think is necessary to better understand your problem.
Have a nice day!
Kind regards!
Support Team.

**Comment by bbhxwl** [comment]
> Dear @bbhxwl ! Thank you for contacting us. To better understand your situation, please, we require the following information:
> 
> Could you explain your problem a little more? Since from what I understand the code does not compile you in that line of code. Can I have the error message? Have you had this problem before? If so, when? Has anything changed since this issue started? Do you experience this issue on another computer\device\network? What IDE are you using and what version of it?
> 
> In the same way, we require you to send us any photograph or video that you think is necessary to better understand your problem. Have a nice day! Kind regards! Support Team.

I use vscode+plaformIO 2.0.4


The code can only run before this sentence, and will not run after this sentence, and there is no error prompt.

**Comment by Eric286** [comment]
Hello @bbhxwl !

This may be due to the fact that the library was not installed correctly and it does not know how to interpret that line.
Could you please try the program in the Arduino IDE?
Also, with any of the examples does this error happen to you?
Also please try to check the example MPU6050_raw.ino and tell me if it works for you.

**Comment by bbhxwl** [comment]
> Hello @bbhxwl !
> 
> This may be due to the fact that the library was not installed correctly and it does not know how to interpret that line. Could you please try the program in the Arduino IDE? Also, with any of the examples does this error happen to you? Also please try to check the example MPU6050_raw.ino and tell me if it works for you.

![image](https://user-images.githubusercontent.com/26525599/191146572-ff7c5fe7-bb56-4ec5-8359-626379e2dcc6.png)
The same, infinite waiting.

**Comment by bbhxwl** [comment]
> Hello @bbhxwl !
> 
> This may be due to the fact that the library was not installed correctly and it does not know how to interpret that line. Could you please try the program in the Arduino IDE? Also, with any of the examples does this error happen to you? Also please try to check the example MPU6050_raw.ino and tell me if it works for you.

Arduino must be OK. I always use this.

**Comment by bbhxwl** [comment]
> Hello @bbhxwl !
> 
> This may be due to the fact that the library was not installed correctly and it does not know how to interpret that line. Could you please try the program in the Arduino IDE? Also, with any of the examples does this error happen to you? Also please try to check the example MPU6050_raw.ino and tell me if it works for you.

![image](https://user-images.githubusercontent.com/26525599/191146708-0b5afec3-6412-4e24-acc6-6a46d441159c.png)
Can it be repaired?

**Comment by bbhxwl** [comment]
> Hello @bbhxwl !
> 
> This may be due to the fact that the library was not installed correctly and it does not know how to interpret that line. Could you please try the program in the Arduino IDE? Also, with any of the examples does this error happen to you? Also please try to check the example MPU6050_raw.ino and tell me if it works for you.

![image](https://user-images.githubusercontent.com/26525599/191147409-146bfe8f-dce4-4844-95aa-ca7ab9483194.png)

**Comment by Eric286** [comment]
Hello @bbhxwl !

Sorry for my late response.

"Can it be repaired?"

-Please give me some time to test it and see, if necessary, how to fix it or what should be done to fix it.

**Comment by Eric286** [comment]
Dear @bbhxwl !

I have already done the tests and this is what I found.
All lines of code worked for me, however, the way I can replicate your error was by disconnecting the voltage from the sensor, with this it always stays on the same line as you.
A very big possibility is that your module is damaged since the code worked perfectly with the same characteristics that you sent me in the last messages.

**Comment by bbhxwl** [comment]
> Dear @bbhxwl !
> 
> I have already done the tests and this is what I found. All lines of code worked for me, however, the way I can replicate your error was by disconnecting the voltage from the sensor, with this it always stays on the same line as you. A very big possibility is that your module is damaged since the code worked perfectly with the same characteristics that you sent me in the last messages.

It can't be broken. I can use arduino ide esp32 1.0.6 to run normally.

**Comment by Eric286** [comment]
Hello @bbhxwl !

Could you check if you don't have some other libraries called MPU6050 that may be interfering? since in all the tests that I have done, it does not happen to me like you, seeing that it is not a problem of the library.

Do you have the Arduino extension in VSCode?

**Comment by bbhxwl** [comment]
> Hello @bbhxwl !
> 
> Could you check if you don't have some other libraries called MPU6050 that may be interfering? since in all the tests that I have done, it does not happen to me like you, seeing that it is not a problem of the library.
> 
> Do you have the Arduino extension in VSCode?

plaformIO
![image](https://user-images.githubusercontent.com/26525599/191636094-024d5683-f8d8-4eca-9104-11dc54a83799.png)

**Comment by Eric286** [comment]
Hello @bbhxwl !

Can you please install this extension and follow the instructions I will give you to solve the problem?

![image](https://user-images.githubusercontent.com/40640735/191794407-857d47f8-1754-4f6e-8846-40259cd71343.png)

After installing this extension please upload the sketch you like for example I uploaded the example called MPU6050_DMP6.ino

![image](https://user-images.githubusercontent.com/40640735/191795503-ea2c7a84-9200-4dcf-987d-cbe5729d25c5.png)

You can do all this in the bottom bar of VScode, make sure that the board is correct as well as the port.

![image](https://user-images.githubusercontent.com/40640735/191795859-fb43fe7f-d463-4ea3-9e7b-6093854ebc09.png)

![image](https://user-images.githubusercontent.com/40640735/191796182-74be10fa-e4c2-4da4-9111-166fc8dc7672.png)

At the top, the symbol must appear to be able to compile the program.

![image](https://user-images.githubusercontent.com/40640735/191801256-b4f55170-97d3-4d76-9294-b0ca2eca9b54.png)

And then you should be able to see the console. And it shouldn't stay on the mpu.initialize();

**Comment by Eric286** [comment]
Hello @bbhxwl!

Is your issue solved?

Best regards!
Support Team.

**Comment by bbhxwl** [comment]
> Hello @bbhxwl!
> 
> Is your issue solved?
> 
> Best regards! Support Team.

No, I still use the 1 version temporarily, instead of the 2 version.

**Comment by Eric286** [comment]
Hello @bbhxwl !

Could you tell me what you mean by the first version or what you mean by this?

**Comment by Eric286** [comment]
Hello @bbhxwl !

Can we close the issue?

**Comment by Eric286** [comment]
Hello @bbhxwl!

We will now close this issue.

In case you have any problems or comments, do not hesitate to contact us again.

Have an amazing day!

Kind regards!
Support Team.
