### ISSUE TITLE
MPu6050 register map revision dont have all registers

### ISSUE THREAD

**Issue by linxcow** [ElectronicCats/mpu6050#60]
Your library is based on register map rev 2.0 documentation but i cant find this version of the documentation.

example : Register 0x1F ( 31 ) is not  mentioned in the register map documents i found. ( setting motion detect threshold )

I know production is stopped but still a lot of GY521 (clones ?) are sold these days.

Edit : This is not an issue with the library but a kind request to receive the doc 2.0 the library is based on.

Below is the document i found that misses a lot of information:

[MPU6050 register map rev 4.2](https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Register-Map1.pdf)

Also the DMP specification was officially released in 2014 , but i cant find the document either.

**Comment by Eric286** [comment]
Hello @linxcow!

Thank you for bringing this to our attention, we truly appreciate your interest in the library.

We assure you that we take your request seriously, and we will thoroughly investigate the differences and work towards upgrading our library to provide the most accurate and up-to-date information possible.

If there are any other questions or clarifications you seek, please don't hesitate to reach out to us. We are here to help you in any way we can.

Best regards,

Support Team!

**Comment by Eric286** [comment]
Hello @linxcow!

If you want to find more information about the library, please go to the following repository, from which we rely, for more information.

We do not have the document you require.

https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050

Best Regards!
