### ISSUE TITLE
Doc [enhancement]: Open the processing sketch (Teapot).

### ISSUE THREAD

**Issue by mw66** [ElectronicCats/mpu6050#73]
https://github.com/ElectronicCats/mpu6050/wiki/4.-Examples#dmp-examples

what's the command for this (on Linux):

step 5: Open the processing sketch (Teapot).

step 8: Run the processing sketch.

**Comment by mw66** [comment]
found answer here:

https://forum.arduino.cc/t/mpu6050-electronic-cats-library-example-does-not-compile/1143806/7

BTW, the `~/Processing/libraries/` name on Linux is: `~/sketchbook/libraries/`.

**Comment by mw66** [comment]
However for 

step 8: Run the processing sketch.

I got error: MPUTeapot.pde:77:0:77:0: RuntimeException: Error opening serial port /dev/ttyUSB0: Port busy

**Comment by xpeqex** [comment]
Hi @mw66 

Thank you for sharing this feedback. These comments are really helpful for a better guidance in the use of the library and its examples. I will add these in the Wiki.

Feel free to open a new issue if you have any other suggestions!

 
<p align=right>
<img src="https://github.com/ElectronicCats/mpu6050/assets/107638696/e68784a5-ef53-4fbd-93df-cacb582cdec2" width=150 />
</p>
