### ISSUE TITLE
Gyroscope 

### ISSUE THREAD

**Issue by Navaneeth272001** [ElectronicCats/mpu6050#76]
Hi ,
Gyroscope calibration routines doesn't work properly ,   when it it subjected to constant angular velocity  the module is not able to recognize the same angular velocity when mounted in different orientations . 
Can you please verify this at different range of gyroscope as well ??

Note: We restarted each time when it is mounted at different orientations, and we waited for it calibration ( though the accelerometer is getting calibrated properly , gyroscope didn't calibrate for the new orientation ) 

Thanks.

**Comment by xpeqex** [comment]
Hi @Navaneeth272001 

Please share with me the following, so I can better understand the issue:
- Version of the library you are using.
- What board are you using.
- What code are you using.
- If possible a picture of the setup you have. 

Regards,

**Comment by Navaneeth272001** [comment]
Hi

Version of the library - 1.3.0
![Screenshot 2024-01-25 121400](https://github.com/ElectronicCats/mpu6050/assets/113966455/feabd96b-237f-4548-b202-b17c85a8b563)

Board - MPU6050 with ESP32

Code - I am using the code MPU6050_raw but called the functions    accelgyro.CalibrateGyro(); and
  accelgyro.CalibrateAccel(); in the setup. 
  
The  accelgyro.CalibrateAccel(); function is working as expected. But  accelgyro.CalibrateGyro(); function seems to be not working. That is, if the MPU6050 module is positioned differently and started, the gyroscope values does not go to zero with respect to that position.

![image](https://github.com/ElectronicCats/mpu6050/assets/113966455/b71e065e-bddf-410e-9331-3ffdd3d30803)

**Comment by xpeqex** [comment]
@Navaneeth272001 

It is hard for me to try to replicate this without a complete code. Could you please share with me? 

Is using the RAW example you may want to disable the DMP to avoid interference with your code.

**Comment by Navaneeth272001** [comment]
First of all I would like to understand how gyroscope calibration works.
Please let me know what happens when the gyroscope calibration function is
called?

**Comment by xpeqex** [comment]
Sure @Navaneeth272001 
You can check the complete routine of the calibration functions here:

https://github.com/ElectronicCats/mpu6050/blob/d81945514fc9c527403179072a5faf029054edab/src/MPU6050.cpp#L3360-L3453

Basically:

- Uses PID control to adjust gyroscope offsets.
- Accelerometer calibration uses different PID gains and addresses for accelerometer offsets.

- Looping Through Calibration Cycles:

  - Iterates through the specified number of Loops.
    - **Within each loop**:
      - Performs 100 PI calculations.
      - Reads sensor data repeatedly.
      - Calculates error and updates PID terms (proportional and integral).
      - Computes new calibration offsets.
      - Writes offsets back to sensor registers.
      - Checks for convergence and adjusts PID gains if necessary.

    - **Finalization**:
      - Resets the FIFO (First-In-First-Out) buffer and DMP (Digital Motion Processor) on the MPU6050.

**Comment by Navaneeth272001** [comment]
Thanks for the details. I understood the code flow, but I would like to understand further into what is the impact of "CalibrateGyro" function on the outputs "gx, gy and gz". How will the outputs "gx, gy and gz" differ when the "CalibrateGyro" is called and when it is not called. Will there be any difference in the output? if so, under what condition the outputs will vary when the function is called and when it is not called. 

I am not able see any difference between the outputs "gx, gy and gz", when the function is called and when it is not called. To understand the work of the function, I would like to do an experiment to see the changes caused due to the calibration routine in the output when the "CalibrateGyro" is called and when it is not called. Please let me know how can I do it.

Thanks

**Comment by xpeqex** [comment]
@Navaneeth272001 

Setting the offset instantly has an effect on the readings. When the MPU6050 is level and stable the calibration samples the sensors and shifts the offsets to get Zeros on 5 of the 6 axis and adjusts Accell Z to show 1g.

Our ability to give advice and support questions related to general project-based queries is limited. Additionally, since this repository is a fork to isolate the MPU6050 usage, we recommend you post it on the original repository https://github.com/jrowberg/i2cdevlib since queries like this can be answered by many people and different solutions can be explored. Also, this will help the community to grow, which will ultimately benefit users.

**Comment by Navaneeth272001** [comment]
Thanks for your time and answers!
