### ISSUE TITLE
Arduino DUE error : '_BV' was not declared in this scope

### ISSUE THREAD

**Issue by brian208579** [ElectronicCats/mpu6050#8]
Hi @sabas1080 

When I excute the MPU6050_DMP6 on Arduino DUE , I got the error : '_BV' was not declared in this scope

What can I fixed it ?
 
Apperciate

**Comment by sabas1080** [comment]
Hi @brian208579 

seems to be an error in ARM M0 architectures, I'm going to check it

**Comment by sabas1080** [comment]
Hi @brian208579 

I have fixed it in the commit https://github.com/ElectronicCats/mpu6050/commit/9f08c14ed6ba40443336fb50b2f579f2c535fc3b

I have replaced _BV to support M0

I await your feedback
