### ISSUE TITLE
ElectronicCats, switch initialize method

### ISSUE THREAD

**Issue by stefcarpi** [ElectronicCats/mpu6050#87]
In the initialize method there is no break statement in the switch for accelRange and gyroRange: the resolution is always set to the maximum available range. It should be fixed. 

`

void MPU6050_Base::initialize(ACCEL_FS accelRange, GYRO_FS gyroRange) {
    setClockSource(MPU6050_CLOCK_PLL_XGYRO);

    switch (accelRange) 
    {
    case ACCEL_FS::A2G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_2);
        accelerationResolution = 2.0 / 16384.0;

    case ACCEL_FS::A4G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_4);
        accelerationResolution = 4.0 / 16384.0;

    case ACCEL_FS::A8G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_8);
        accelerationResolution = 8.0 / 16384.0;

    case ACCEL_FS::A16G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_16);
        accelerationResolution = 16.0 / 16384.0;
    }

    switch (gyroRange) 
    {
    case GYRO_FS::G250DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_250);
        gyroscopeResolution = 250.0 / 16384.0;

    case GYRO_FS::G500DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_500);
        gyroscopeResolution = 500.0 / 16384.0;

    case GYRO_FS::G1000DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_1000);
        gyroscopeResolution = 1000.0 / 16384.0;

    case GYRO_FS::G2000DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_2000);
        gyroscopeResolution = 2000.0 / 16384.0;
    }

    setSleepEnabled(false); // thanks to Jack Elston for pointing this one out!
}`

**Comment by sabas1080** [comment]
#88
