### ISSUE TITLE
ADC resolution

### ISSUE THREAD

**Issue by stefcarpi** [ElectronicCats/mpu6050#89]
Hello!
It seems there is a problem with the resolution computation. 
The accelerometer or gyroscope resolution is computed in the library dividing the full range by 16384. 
The division should be instead by 32768, which is half of the values available from the 16bit ADC. 
The resolution is also the inverse of the sensitivity reported in the datasheet, for example 
sensitivity = 16384 LSB/g = 32738/2g. The same for the other values  

switch (accelRange) 
    {
    case ACCEL_FS::A2G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_2);
        accelerationResolution = 2.0 / 16384.0;
	break;

    case ACCEL_FS::A4G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_4);
        accelerationResolution = 4.0 / 16384.0;
	break;

    case ACCEL_FS::A8G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_8);
        accelerationResolution = 8.0 / 16384.0;
	break;

    case ACCEL_FS::A16G:
        setFullScaleAccelRange(MPU6050_ACCEL_FS_16);
        accelerationResolution = 16.0 / 16384.0;
	break;
    default:
      Serial.println("Init accelRange not valid, setting maximum accel range");
      setFullScaleAccelRange(MPU6050_ACCEL_FS_16);
      accelerationResolution = 16.0 / 16384.0;
    }

    switch (gyroRange) 
    {
    case GYRO_FS::G250DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_250);
        gyroscopeResolution = 250.0 / 16384.0;
	break;

    case GYRO_FS::G500DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_500);
        gyroscopeResolution = 500.0 / 16384.0;
	break;

    case GYRO_FS::G1000DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_1000);
        gyroscopeResolution = 1000.0 / 16384.0;
	break;

    case GYRO_FS::G2000DPS:
        setFullScaleGyroRange(MPU6050_GYRO_FS_2000);
        gyroscopeResolution = 2000.0 / 16384.0;
	break;
    default:
      Serial.println("Init gyroRange not valid, setting maximum gyro range");
      setFullScaleGyroRange(MPU6050_GYRO_FS_2000);
      gyroscopeResolution = 2000.0 / 16384.0;
    }

**Comment by xpeqex** [comment]
Hi @stefcarpi 

Thank you for reaching out and providing detailed feedback.

You are correct that the resolution calculation for the accelerometer and gyroscope should reflect the 16-bit ADC, which gives a range of values from -32768 to 32767. The resolution should indeed be calculated by dividing the full range by 32768, rather than 16384 as currently implemented.

Also, thank you for opening the PR, we will take a look at it before merging. 

I will close this issue.
